language: php

php:
    - 5.4
    - 5.5

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev --prefer-source
    - mkdir -p web/code-coverage

after_script:
    - git checkout --orphan gh-pages
    - git rm -rf .
    - git add web/code-coverage
    - git commit -a -m "Update code coverage"
    - git push origin gh-pages

script:
    - bin/atoum --test-all

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change