language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer self-update || true
    - composer install --dev --prefer-source
    - mkdir -p web/code-coverage data
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    - bin/atoum

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover data/coverage.clover

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
